# Generated by Django 4.1.5 on 2023-01-31 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TN', 'Танк'), ('HL', 'Хил'), ('DD', 'ДД'), ('TG', 'Торговец'), ('GM', 'Гилдмастер'), ('KG', 'Квестгивер'), ('KZ', 'Кузнец'), ('KV', 'Кожевник'), ('ZL', 'Зельевар'), ('MZ', 'Мастер заклинаний')], default='TN', max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('time_creating', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('W', 'На рассмотрении'), ('A', 'Принят'), ('R', 'Удален')], default='W', max_length=1)),
                ('time_creating', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.announcement')),
                ('responser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
